### ISSUE TITLE
 Model class "Application\Sonata\UserBundle\Entity\User" does not correspond to manager type "orm". 

### ISSUE THREAD

**Issue by maavia10** [sonata-project/SonataUserBundle#1071]
i a facing this issue

```
 sonata_user:
   security_acl: true
   manager_type: orm
   class:
      user: Application\Sonata\UserBundle\Entity\User
      group: Application\Sonata\UserBundle\Entity\Group
```
```
fos_user:
  db_driver:      orm # can be orm or odm
  firewall_name:  main
  user_class:     Application\Sonata\UserBundle\Entity\User

  group:
    group_class:   Application\Sonata\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

  service:
    user_manager: sonata.user.orm.user_manager
  from_email:
    address: "hello@youmail.com"
    sender_name: "Sender Name"
```
on symfony 4.2
