### ISSUE TITLE
Attempted to load class "BaseUser" from namespace "App\Application\Sonata\UserBundle\Entity"

### ISSUE THREAD

**Issue by jcRisch** [sonata-project/SonataUserBundle#1075]
#### Sonata packages

```
sonata-project/admin-bundle              3.45.1 3.45.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0 3.14.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.15.1 3.15.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.1  3.8.1  Symfony Sonata / Integrate Doctrine ORM into t...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.0 1.11.0 Lightweight Exporter library
sonata-project/media-bundle              3.18.1 3.18.1 Symfony SonataMediaBundle
sonata-project/user-bundle               4.2.3  4.2.3  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/apache-pack          v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                v3.4.21 v3.4.21 Symfony Asset Component
symfony/cache                v3.4.21 v3.4.21 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.21 v3.4.21 Symfony ClassLoader Component
symfony/config               v3.4.21 v3.4.21 Symfony Config Component
symfony/console              v3.4.21 v3.4.21 Symfony Console Component
symfony/debug                v3.4.21 v3.4.21 Symfony Debug Component
symfony/dependency-injection v3.4.21 v3.4.21 Symfony DependencyInjection Component
symfony/doctrine-bridge      v3.4.21 v3.4.21 Symfony Doctrine Bridge
symfony/dotenv               v3.4.21 v3.4.21 Registers environment variables from a .env file
symfony/event-dispatcher     v3.4.21 v3.4.21 Symfony EventDispatcher Component
symfony/expression-language  v3.4.21 v3.4.21 Symfony ExpressionLanguage Component
symfony/filesystem           v3.4.21 v3.4.21 Symfony Filesystem Component
symfony/finder               v3.4.21 v3.4.21 Symfony Finder Component
symfony/flex                 v1.1.8  v1.1.8  Composer plugin for Symfony
symfony/form                 v3.4.21 v3.4.21 Symfony Form Component
symfony/framework-bundle     v3.4.21 v3.4.21 Symfony FrameworkBundle
symfony/http-foundation      v3.4.21 v3.4.21 Symfony HttpFoundation Component
symfony/http-kernel          v3.4.21 v3.4.21 Symfony HttpKernel Component
symfony/inflector            v3.4.21 v3.4.21 Symfony Inflector Component
symfony/intl                 v3.4.21 v3.4.21 A PHP replacement layer for the C intl extension that in...
symfony/maker-bundle         v1.11.3 v1.11.3 Symfony Maker helps you create empty commands, controlle...
symfony/options-resolver     v3.4.21 v3.4.21 Symfony OptionsResolver Component
symfony/orm-pack             v1.0.6  v1.0.6  A pack for the Doctrine ORM
symfony/polyfill-apcu        v1.10.0 v1.10.0 Symfony polyfill backporting apcu_* functions to lower P...
symfony/polyfill-intl-icu    v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/process              v3.4.21 v3.4.21 Symfony Process Component
symfony/property-access      v3.4.21 v3.4.21 Symfony PropertyAccess Component
symfony/routing              v3.4.21 v3.4.21 Symfony Routing Component
symfony/security             v3.4.21 v3.4.21 Symfony Security Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v3.4.21 v3.4.21 Symfony SecurityBundle
symfony/stopwatch            v3.4.21 v3.4.21 Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.5  v3.2.5  Symfony SwiftmailerBundle
symfony/templating           v3.4.21 v3.4.21 Symfony Templating Component
symfony/translation          v3.4.21 v3.4.21 Symfony Translation Component
symfony/twig-bridge          v3.4.21 v3.4.21 Symfony Twig Bridge
symfony/twig-bundle          v3.4.21 v3.4.21 Symfony TwigBundle
symfony/validator            v3.4.21 v3.4.21 Symfony Validator Component
symfony/web-server-bundle    v3.4.21 v3.4.21 Symfony WebServerBundle
symfony/yaml                 v3.4.21 v3.4.21 Symfony Yaml Component
```

#### PHP version

```
PHP 7.1.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan 11 2019 14:13:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.26-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

Can't register a user using FOSUserBundle + SonataUserBundle. 
I installed succefully SonataUserBundle using the official [doc](https://sonata-project.org/bundles/user/master/doc/reference/installation.html). My bdd is updated, everything is ok but I can't access to the `/register` page. Error below. 

## Actual results

```
Attempted to load class "BaseUser" from namespace "App\Application\Sonata\UserBundle\Entity".
Did you forget a "use" statement for e.g. "Sonata\UserBundle\Entity\BaseUser" or "Sonata\UserBundle\Document\BaseUser"?
```
Stack Trace : 
```
Symfony\Component\Debug\Exception\ClassNotFoundException:
Attempted to load class "BaseUser" from namespace "App\Application\Sonata\UserBundle\Entity".
Did you forget a "use" statement for e.g. "Sonata\UserBundle\Entity\BaseUser" or "Sonata\UserBundle\Document\BaseUser"?

  at vendor/friendsofsymfony/user-bundle/Model/UserManager.php:40
  at FOS\UserBundle\Model\UserManager->createUser()
     (vendor/friendsofsymfony/user-bundle/Controller/RegistrationController.php:59)
  at FOS\UserBundle\Controller\RegistrationController->registerAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

## More infos
Config : 
```
sonata_user:
    security_acl: true
    manager_type: orm
    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Application\Sonata\UserBundle\Entity\BaseUser
    group:
        group_class:   App\Application\Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager
    from_email:
        address: "meh@website.fr"
        sender_name: "My App"
    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: sonata.user.orm.user_manager
    registration:
        confirmation:
            enabled: true
            from_email:
                address: label@elter.fr
                sender_name: Label Online App
            template: 'user/registration.email.twig'
```
User.php : 
```
<?php

namespace App\Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
}
```
Part of composer.json : 
```
"autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
```

Thank you,
