### ISSUE TITLE
After install and changes to config: Unable to generate a URL for the named route "admin_sonata_user_baseuser_create"

### ISSUE THREAD

**Issue by roelveldhuizen** [sonata-project/SonataUserBundle#1087]
### Environment
Apache 2.4 PHP via FPM. 
Windows 10
Development machine. 

#### Sonata packages

```
sonata-project/admin-bundle              3.48.0 3.48.0 The missing Symfony Admin Generator                                                                                                sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBundle                                                                                                          sonata-project/cache                     2.0.1  2.0.1  Cache library                                                                                                                      sonata-project/core-bundle               3.16.2 3.16.2 Symfony SonataCoreBundle                                                                                                           sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagridBundle                                                                                                       sonata-project/doctrine-extensions       1.2.0  1.2.0  Doctrine2 behavioral extensions                                                                                                    sonata-project/doctrine-orm-admin-bundle 3.8.3  3.8.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdmin...                                                                    sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle                                                                                                    sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library                                                                                                       sonata-project/google-authenticator      2.2.0  2.2.0  Library to integrate Google Authenticator into a PHP project                                                                       sonata-project/user-bundle               4.3.0  4.3.0  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/asset                 v4.1.11 v4.1.11 Symfony Asset Component                                                                                                                     symfony/browser-kit           v4.1.11 v4.1.11 Symfony BrowserKit Component                                                                                                                symfony/cache                 v4.1.11 v4.1.11 Symfony Cache component with PSR-6, PSR-16, and tags                                                                                        symfony/config                v4.1.11 v4.1.11 Symfony Config Component                                                                                                                    symfony/console               v4.1.11 v4.1.11 Symfony Console Component                                                                                                                   symfony/contracts             v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components                                                                               symfony/css-selector          v4.1.11 v4.1.11 Symfony CssSelector Component                                                                                                               symfony/debug                 v4.1.11 v4.1.11 Symfony Debug Component                                                                                                                     symfony/debug-bundle          v4.1.11 v4.1.11 Symfony DebugBundle                                                                                                                         symfony/debug-pack            v1.0.7  v1.0.7  A debug pack for Symfony projects                                                                                                           symfony/dependency-injection  v4.1.11 v4.1.11 Symfony DependencyInjection Component                                                                                                       symfony/doctrine-bridge       v4.1.11 v4.1.11 Symfony Doctrine Bridge                                                                                                                     symfony/dom-crawler           v4.1.11 v4.1.11 Symfony DomCrawler Component                                                                                                                symfony/dotenv                v4.1.11 v4.1.11 Registers environment variables from a .env file                                                                                            symfony/event-dispatcher      v4.1.11 v4.1.11 Symfony EventDispatcher Component                                                                                                           symfony/expression-language   v4.1.11 v4.1.11 Symfony ExpressionLanguage Component                                                                                                        symfony/filesystem            v4.1.11 v4.1.11 Symfony Filesystem Component                                                                                                                symfony/finder                v4.1.11 v4.1.11 Symfony Finder Component                                                                                                                    symfony/flex                  v1.2.1  v1.2.1  Composer plugin for Symfony                                                                                                                 symfony/form                  v4.1.11 v4.1.11 Symfony Form Component                                                                                                                      symfony/framework-bundle      v4.1.11 v4.1.11 Symfony FrameworkBundle                                                                                                                     symfony/http-foundation       v4.1.11 v4.1.11 Symfony HttpFoundation Component                                                                                                            symfony/http-kernel           v4.1.11 v4.1.11 Symfony HttpKernel Component                                                                                                                symfony/inflector             v4.1.11 v4.1.11 Symfony Inflector Component                                                                                                                 symfony/intl                  v4.1.11 v4.1.11 A PHP replacement layer for the C intl extension that includes additi...                                                                    symfony/maker-bundle          v1.11.5 v1.11.5 Symfony Maker helps you create empty commands, controllers, form clas...                                                                    symfony/monolog-bridge        v4.1.11 v4.1.11 Symfony Monolog Bridge                                                                                                                      symfony/monolog-bundle        v3.3.1  v3.3.1  Symfony MonologBundle                                                                                                                       symfony/options-resolver      v4.1.11 v4.1.11 Symfony OptionsResolver Component                                                                                                           symfony/orm-pack              v1.0.6  v1.0.6  A pack for the Doctrine ORM                                                                                                                 symfony/panther               v0.3.0  v0.3.0  A browser testing and web scraping library for PHP and Symfony.                                                                             symfony/phpunit-bridge        v4.2.5  v4.2.5  Symfony PHPUnit Bridge                                                                                                                      symfony/polyfill-intl-icu     v1.11.0 v1.11.0 Symfony polyfill for intl's ICU-related data and classes                                                                                    symfony/polyfill-intl-idn     v1.11.0 v1.11.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions                                                                          symfony/polyfill-mbstring     v1.11.0 v1.11.0 Symfony polyfill for the Mbstring extension                                                                                                 symfony/polyfill-php72        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP vers...                                                                    symfony/process               v4.1.11 v4.1.11 Symfony Process Component                                                                                                                   symfony/profiler-pack         v1.0.4  v1.0.4  A pack for the Symfony web profiler                                                                                                         symfony/property-access       v4.1.11 v4.1.11 Symfony PropertyAccess Component                                                                                                            symfony/property-info         v4.1.11 v4.1.11 Symfony Property Info Component                                                                                                             symfony/routing               v4.1.11 v4.1.11 Symfony Routing Component                                                                                                                   symfony/security              v4.1.11 v4.1.11 Symfony Security Component                                                                                                                  symfony/security-acl          v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)                                                                                      symfony/security-bundle       v4.1.11 v4.1.11 Symfony SecurityBundle                                                                                                                      symfony/serializer            v4.1.11 v4.1.11 Symfony Serializer Component                                                                                                                symfony/serializer-pack       v1.0.2  v1.0.2  A pack for the Symfony serializer                                                                                                           symfony/stopwatch             v4.1.11 v4.1.11 Symfony Stopwatch Component                                                                                                                 symfony/swiftmailer-bundle    v3.2.5  v3.2.5  Symfony SwiftmailerBundle                                                                                                                   symfony/templating            v4.1.11 v4.1.11 Symfony Templating Component                                                                                                                symfony/test-pack             v1.0.5  v1.0.5  A pack for functional and end-to-end testing within a Symfony app                                                                           symfony/translation           v4.1.11 v4.1.11 Symfony Translation Component                                                                                                               symfony/twig-bridge           v4.1.11 v4.1.11 Symfony Twig Bridge                                                                                                                         symfony/twig-bundle           v4.1.11 v4.1.11 Symfony TwigBundle                                                                                                                          symfony/validator             v4.1.11 v4.1.11 Symfony Validator Component                                                                                                                 symfony/var-dumper            v4.1.11 v4.1.11 Symfony mechanism for exploring and dumping PHP variables                                                                                   symfony/web-link              v4.1.11 v4.1.11 Symfony WebLink Component                                                                                                                   symfony/web-profiler-bundle   v4.1.11 v4.1.11 Symfony WebProfilerBundle                                                                                                                   symfony/web-server-bundle     v4.1.11 v4.1.11 Symfony WebServerBundle                                                                                                                     symfony/webpack-encore-bundle v1.4.0  v1.4.0  Integration with your Symfony app & Webpack Encore!                                                                                         symfony/yaml                  v4.1.11 v4.1.11 Symfony Yaml Component
```

#### PHP version

```
PHP 7.2.15 (cli) (built: Feb  5 2019 22:54:26) ( ZTS MSVC15 (Visual C++ 2017) x64 )                                                                                                       Copyright (c) 1997-2018 The PHP Group                                                                                                                                                     Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies                                                                                                                                 with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```

## Subject
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_sonata_user_baseuser_create" as such route does not exist.").

I installed fos user first then after a while wanted to enable sonata admin.

## Steps to reproduce
1. Installed and configured fos user bundle. (worked correctly).
2. Installed sonata admin (worked correctly).
3. Installed sonata user bundle. (following this documentation https://sonata-project.org/bundles/user/4-x/doc/reference/installation.html )
4. Generated user and group classes via easy-extend
5. Made some changes to the config (share config bellow). Most changes involve using my User entity instead of the Sonata generated.
6. Removed the generated User class
7. Login as a existing user. 
8. Get the exception "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_sonata_user_baseuser_create" as such route does not exist.").
9. When not going to the /admin (sonata admin) everything seems to work correctly. So is seems to break only when opening the admin. 

## Expected results
Being able to login and see the sonata admin again. 

## Actual results
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_sonata_user_baseuser_create" as such route does not exist.").

## Some configs

fos_user;
```
fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: test@xxx.nl
    sender_name: ZINnig

  group:
    group_class:   App\Application\Sonata\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

  service:
    user_manager: sonata.user.orm.user_manager
```
security;
```
security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers


  role_hierarchy:
    ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    SONATA:
      - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    main:
      pattern: ^/
      user_checker: security.user_checker
      form_login:
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager

      logout:       true
      anonymous:    true

  access_control:

    # Admin login page needs to be accessed without credential
    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/l/, role: ROLE_USER }
    - { path: ^/dossier/, role: ROLE_USER }
    - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
```

sonata_admin;
```
sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_javascripts:
            # ...
            - bundles/fosckeditor/ckeditor.js

        extra_stylesheets:
            # ...

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
```

sonata_user.yml;
```

sonata_user:
  manager_type: orm # can be orm or mongodb


  class:
    user:    App\Entity\User
    group:   App\Application\Sonata\UserBundle\Entity\Group
```

routes.yml
```
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\DefaultController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /admin/resetting

```

sontat_admin.yml (routes);
```
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

```
