### ISSUE TITLE
No metadata found for property CoreBundle\\Entity\\User::$username

### ISSUE THREAD

**Issue by dcatz** [sonata-project/SonataUserBundle#1358]
#### Sonata packages

```
sonata-project/admin-bundle              3.98.1             3.104.0            The missing Symfony Admin Generator
sonata-project/block-bundle              3.21.0             4.6.0              Symfony SonataBlockBundle
sonata-project/cache                     2.0.1              2.2.0              Cache library
sonata-project/core-bundle               3.20.0             3.20.0             Symfony SonataCoreBundle (abandoned)
Package sonata-project/core-bundle is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/datagrid-bundle           3.3.0              3.3.0              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.12.0             1.13.1             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.17.1             3.35.0             Symfony Sonata / Integrate Doctrine ORM into the SonataAdmin...
sonata-project/easy-extends-bundle       2.5.0              2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.6.2              2.7.0              Lightweight Exporter library
sonata-project/form-extensions           0.1.2              1.9.0              Symfony form extensions
sonata-project/media-bundle              dev-master be69e4b dev-master ee04bf8 Symfony SonataMediaBundle
sonata-project/translation-bundle        2.8.0              2.8.1              SonataTranslationBundle
sonata-project/twig-extensions           0.1.1              1.7.0              Sonata twig extensions
sonata-project/user-bundle               4.11.1             4.11.1             Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/asset                      v4.4.19 v5.3.4  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript ...
symfony/browser-kit                v4.4.19 v5.3.4  Simulates the behavior of a web browser, allowing you to make requests, click on links a...
symfony/cache                      v4.4.19 v5.3.4  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v4.4.20 v5.3.4  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v4.4.20 v5.3.6  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v4.4.19 v5.3.4  Converts CSS selectors to XPath expressions
symfony/debug                      v4.4.19 v4.4.27 Provides tools to ease debugging PHP code
symfony/debug-bundle               v4.4.19 v5.3.4  Provides a tight integration of the Symfony Debug component into the Symfony full-stack ...
symfony/debug-pack                 v1.0.9  v1.0.9  A debug pack for Symfony projects
symfony/dependency-injection       v4.4.20 v5.3.4  Allows you to standardize and centralize the way objects are constructed in your applica...
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.19 v5.3.4  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v4.4.19 v5.3.4  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v4.4.19 v5.3.6  Registers environment variables from a .env file
symfony/error-handler              v4.4.19 v5.3.4  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v4.4.20 v5.3.4  Provides tools that allow your application components to communicate with each other by ...
symfony/event-dispatcher-contracts v1.1.9  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.19 v5.3.4  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v4.4.19 v5.3.4  Provides basic utilities for the filesystem
symfony/finder                     v4.4.19 v5.3.4  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.10.0 v1.13.4 Composer plugin for Symfony
symfony/form                       v4.4.19 v5.3.4  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.19 v5.3.4  Provides a tight integration between Symfony components and the Symfony full-stack frame...
symfony/http-client                v4.4.19 v5.3.4  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.19 v5.3.6  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v4.4.20 v5.3.6  Provides a structured process for converting a Request into a Response
symfony/inflector                  v4.4.19 v5.3.4  Converts words between their singular and plural forms (English only)
Package symfony/inflector is abandoned, you should avoid using it. Use use `EnglishInflector` from the String component instead instead.
symfony/intl                       v4.4.19 v5.3.4  Provides a PHP replacement layer for the C intl extension that includes additional data ...
symfony/mailer                     v4.4.19 v5.3.4  Helps sending emails
symfony/maker-bundle               v1.29.1 v1.33.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more...
symfony/mercure                    v0.4.1  v0.5.3  Symfony Mercure Component
symfony/mercure-bundle             v0.2.6  v0.3.2  Symfony MercureBundle
symfony/messenger                  v4.4.19 v5.3.4  Helps applications send and receive messages to/from other applications or via message q...
symfony/mime                       v4.4.19 v5.3.4  Allows manipulating MIME messages
symfony/monolog-bridge             v4.4.19 v5.3.4  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.6.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v4.4.19 v5.3.4  Provides an improved replacement for the array_replace PHP function
symfony/orm-pack                   v2.1.0  v2.1.0  A pack for the Doctrine ORM
symfony/phpunit-bridge             v5.2.3  v5.3.4  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.22.1 v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.1 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.22.1 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.22.1 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.1 v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.22.1 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.22.1 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.22.1 v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-uuid              v1.22.1 v1.23.0 Symfony polyfill for uuid functions
symfony/process                    v4.4.19 v5.3.4  Executes commands in sub-processes
symfony/profiler-pack              v1.0.5  v1.0.5  A pack for the Symfony web profiler
symfony/property-access            v4.4.19 v5.3.4  Provides functions to read and write from/to an object or array using a simple string no...
symfony/property-info              v4.4.19 v5.3.4  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v4.4.19 v5.3.4  Provides integration for ProxyManager with various Symfony components
symfony/psr-http-message-bridge    v2.0.2  v2.1.1  PSR HTTP message bridge
symfony/routing                    v4.4.19 v5.3.4  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.2  v3.2.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.19 v5.3.4  Provides a tight integration of the Security component into the Symfony full-stack frame...
symfony/security-core              v4.4.20 v5.3.6  Symfony Security Component - Core Library
symfony/security-csrf              v4.4.19 v5.3.4  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.19 v5.3.4  Symfony Security Component - Guard
symfony/security-http              v4.4.19 v5.3.6  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.4.19 v5.3.4  Handles serializing and deserializing data structures, including object graphs, into arr...
symfony/serializer-pack            v1.0.4  v1.0.4  A pack for the Symfony serializer
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.19 v5.3.4  Provides a way to profile code
symfony/string                     v5.2.8  v5.3.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and g...
symfony/swiftmailer-bundle         v3.5.2  v3.5.2  Symfony SwiftmailerBundle
symfony/templating                 v4.4.19 v5.3.4  Provides all the tools needed to build any kind of template system
symfony/test-pack                  v1.0.7  v1.0.8  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                v4.4.19 v5.3.4  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.19 v5.3.4  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v4.4.20 v5.3.4  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/twig-pack                  v1.0.1  v1.0.1  A Twig pack for Symfony projects
symfony/validator                  v4.4.19 v5.3.6  Provides tools to validate values
symfony/var-dumper                 v4.4.19 v5.3.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v4.4.19 v5.3.4  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v4.4.19 v5.3.4  Manages links between resources
symfony/web-profiler-bundle        v4.4.19 v5.3.5  Provides a development tool that gives detailed information about the execution of any r...
symfony/webpack-encore-bundle      v1.11.0 v1.12.0 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.19 v5.3.6  Loads and dumps YAML files
```

#### Doctrine packages

```
doctrine/annotations                1.13.1 1.13.2 Docblock Annotations Parser
doctrine/cache                      1.11.3 2.1.1  PHP Doctrine Cache library is a popular cache implementation that supports many different...
doctrine/collections                1.6.7  1.6.7  PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     2.13.3 3.1.2  PHP Doctrine Common project is a library that provides additional functionality that othe...
doctrine/data-fixtures              1.5.0  1.5.0  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       2.13.1 3.1.1  Powerful PHP database abstraction layer (DBAL) with many features for database schema int...
doctrine/deprecations               v0.5.3 v0.5.3 A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to...
doctrine/doctrine-bundle            2.3.2  2.4.2  Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle   3.4.0  3.4.0  Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle 3.1.1  3.1.1  Symfony DoctrineMigrationsBundle
doctrine/event-manager              1.1.1  1.1.1  The Doctrine Event Manager is a simple PHP event system that was built to be used with th...
doctrine/inflector                  1.4.3  2.0.3  PHP Doctrine Inflector is a small library that can perform string manipulations with rega...
doctrine/instantiator               1.4.0  1.4.0  A small, lightweight utility to instantiate objects in PHP without invoking their constru...
doctrine/lexer                      1.2.1  1.2.1  PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 3.1.2  3.2.1  PHP Doctrine Migrations project offer additional functionality on top of the database abs...
doctrine/mongodb-odm                2.1.2  2.2.2  PHP Doctrine MongoDB Object Document Mapper (ODM) provides transparent persistence for PH...
doctrine/mongodb-odm-bundle         4.2.2  4.3.0  Symfony2 Doctrine MongoDB Bundle
doctrine/orm                        2.7.5  2.9.3  Object-Relational-Mapper for PHP
doctrine/persistence                1.3.8  2.2.1  The Doctrine Persistence project is a set of shared interfaces and functionality that the...
doctrine/reflection                 1.2.1  1.2.2  The Doctrine Reflection project is a simple library used by the various Doctrine projects...
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
doctrine/sql-formatter              1.1.1  1.1.1  a PHP SQL highlighting library
```

#### PHP version

```
$ php -v
PHP 7.4.22 (cli) (built: Jul 30 2021 13:07:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.22, Copyright (c), by Zend Technologies
```

## Subject

When trying to access the User admin panel and I get the following error:

```
[2021-08-06 17:53:50] request.CRITICAL: Uncaught PHP Exception Sonata\DoctrineORMAdminBundle\Model\MissingPropertyMetadataException: "No metadata found for property `CoreBundle\Entity\User::$username`. Please make sure your Doctrine mapping is properly configured." at /var/www/admin/vendor/sonata-project/doctrine-orm-admin-bundle/src/Guesser/FilterTypeGuesser.php line 78 {"exception":"[object] (Sonata\\DoctrineORMAdminBundle\\Model\\MissingPropertyMetadataException(code: 0): No metadata found for property `CoreBundle\\Entity\\User::$username`. Please make sure your Doctrine mapping is properly configured. at /var/www/admin/vendor/sonata-project/doctrine-orm-admin-bundle/src/Guesser/FilterTypeGuesser.php:78)"} []
```

#### doctrine.yaml

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            sa:
                url: '%env(resolve:DATABASE_SA_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            json:
                class: Sonata\Doctrine\Types\JsonType
                commented: true
            money:
                class: CoreBundle\Types\MoneyType
                commented: true
            money_usd:
                class: CoreBundle\Types\MoneyUSDType
                commented: true

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            auto_mapping: true
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    CoreBundle:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/CoreBundle/Entity'
                        prefix: 'CoreBundle\Entity'
                        alias: App
                    ApiBundle:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/ApiBundle/Entity'
                        prefix: 'ApiBundle\Entity'
                        alias: Api
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Translatable/Entity'
                        alias: GedmoTranslatable
                        is_bundle: false
                    SonataUserBundle: ~
                    SonataMediaBundle: ~
                    FOSUserBundle: ~
                dql:
                    string_functions:
                        FIELD: DoctrineExtensions\Query\Mysql\Field
                    datetime_functions:
                        DATE_FORMAT: CoreBundle\Dql\DateFormat
                        TIME_DIFF: CoreBundle\Dql\TimeDiff
                        TIME_TO_SEC: CoreBundle\Dql\TimeToSec
                        SEC_TO_TIME: CoreBundle\Dql\SecToTime
                        SOUNDEX: CoreBundle\Dql\Soundex
                    numeric_functions:
                        ROUND: CoreBundle\Dql\Round
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            sa:
                connection: sa
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    CoreBundle:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/CoreBundle/Entity'
                        prefix: 'CoreBundle\Entity'
                        alias: App
                    ApiBundle:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/ApiBundle/Entity'
                        prefix: 'ApiBundle\Entity'
                        alias: Api
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: '%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Translatable/Entity'
                        alias: GedmoTranslatable
                        is_bundle: false
                    SonataUserBundle: ~
                    SonataMediaBundle: ~
                    FOSUserBundle: ~
                dql:
                    string_functions:
                        FIELD: DoctrineExtensions\Query\Mysql\Field
                    datetime_functions:
                        DATE_FORMAT: CoreBundle\Dql\DateFormat
                        TIME_DIFF: CoreBundle\Dql\TimeDiff
                        TIME_TO_SEC: CoreBundle\Dql\TimeToSec
                        SEC_TO_TIME: CoreBundle\Dql\SecToTime
                        SOUNDEX: CoreBundle\Dql\Soundex
                    numeric_functions:
                        ROUND: CoreBundle\Dql\Round
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
```

#### fos_user.yaml

```
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: CoreBundle\Entity\User
  group:
    group_class: CoreBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager
  service:
    user_manager: sonata.user.orm.user_manager
  from_email:
    address: "test@domain.com"
    sender_name: "test@domain.com"
```

#### User.php 
(User Entity extending from FOS\UserBundle\Model\User)

```
<?php

namespace CoreBundle\Entity;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

use FOS\UserBundle\Model\User as BaseUser;

/**
 * Class User
 *
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 * @UniqueEntity(fields="email", errorPath="email", message="fos_user.email.already_used")
 *
 * @package CoreBundle\Entity
 */
class User extends BaseUser
{
    /**
     * @var int $id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @var string $firstname
     *
     * @ORM\Column(name="firstname", type="string", length=64, nullable=true)
     */
    protected $firstname;

    /**
     * @var string $lastname
     *
     * @ORM\Column(name="lastname", type="string", length=64, nullable=true)
     */
    protected $lastname;

    /**
     * @var string $locale
     *
     * @ORM\Column(name="locale", type="string", length=8, nullable=true)
     */
    protected $locale;

    /**
     * @var string $timezone
     *
     * @ORM\Column(name="timezone", type="string", length=64, nullable=true)
     */
    protected $timezone;

    /**
     * @var string $phone
     *
     * @ORM\Column(name="phone", type="string", length=64, nullable=true)
     */
    protected $phone;

    /**
     * @var string $twoStepCode
     *
     * @ORM\Column(name="two_step_code", type="string", length=255, nullable=true)
     */
    protected $twoStepCode;

    ...

```

## Steps to reproduce

Install SonataUserBundle and SonataAdmin then open the user list.

## Expected results

Get the user list.

## Actual results

Error:

```
[2021-08-06 17:53:50] request.CRITICAL: Uncaught PHP Exception Sonata\DoctrineORMAdminBundle\Model\MissingPropertyMetadataException: "No metadata found for property `CoreBundle\Entity\User::$username`. Please make sure your Doctrine mapping is properly configured." at /var/www/admin/vendor/sonata-project/doctrine-orm-admin-bundle/src/Guesser/FilterTypeGuesser.php line 78 {"exception":"[object] (Sonata\\DoctrineORMAdminBundle\\Model\\MissingPropertyMetadataException(code: 0): No metadata found for property `CoreBundle\\Entity\\User::$username`. Please make sure your Doctrine mapping is properly configured. at /var/www/admin/vendor/sonata-project/doctrine-orm-admin-bundle/src/Guesser/FilterTypeGuesser.php:78)"} []
```

It's important to note that **I have 2 Entity Managers** and it works correctly with the first one (default) but not with the second one (sa).

Digging into the issue I debugged the ClassMetadata within [FilterTypeGuesser.php](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Guesser/FilterTypeGuesser.php#L44) using the default Entity Manager and this is the result:

```
FilterTypeGuesser.php on line 50:
Doctrine\ORM\Mapping\ClassMetadata {#1171 ▼
  +name: "CoreBundle\Entity\User"
  +namespace: "CoreBundle\Entity"
  +rootEntityName: "CoreBundle\Entity\User"
  +customGeneratorDefinition: null
  +customRepositoryClassName: null
  +isMappedSuperclass: false
  +isEmbeddedClass: false
  +parentClasses: []
  +subClasses: []
  +embeddedClasses: []
  +namedQueries: []
  +namedNativeQueries: []
  +sqlResultSetMappings: []
  +identifier: array:1 [▶]
  +inheritanceType: 1
  +generatorType: 4
  +fieldMappings: array:20 [▼                             <-------
    "username" => array:5 [▼
      "fieldName" => "username"
      "type" => "string"
      "columnName" => "username"
      "length" => 180
      "declared" => "FOS\UserBundle\Model\User"           <-------
    ]
    "usernameCanonical" => array:6 [▶]
    "email" => array:5 [▶]
    "emailCanonical" => array:6 [▶]
    "enabled" => array:4 [▶]
    "salt" => array:5 [▶]
    "password" => array:4 [▶]
    "lastLogin" => array:5 [▶]
    "confirmationToken" => array:7 [▶]
    "passwordRequestedAt" => array:5 [▶]
    "roles" => array:4 [▶]
    "id" => array:9 [▶]
    "firstname" => array:8 [▶]
    "lastname" => array:8 [▶]
    "locale" => array:8 [▶]
    "timezone" => array:8 [▶]
    "phone" => array:8 [▶]
    "twoStepCode" => array:8 [▶]
    "created" => array:8 [▶]
    "updated" => array:8 [▶]
  ]
```

As you can see above there are 20 fields mapped and showing as "declared" in the parent class which is correct.

Now, using the other entity manager (sa)

```
FilterTypeGuesser.php on line 77:
Doctrine\ORM\Mapping\ClassMetadata {#22174 ▼
  +name: "CoreBundle\Entity\User"
  +namespace: "CoreBundle\Entity"
  +rootEntityName: "CoreBundle\Entity\User"
  +customGeneratorDefinition: null
  +customRepositoryClassName: null
  +isMappedSuperclass: false
  +isEmbeddedClass: false
  +parentClasses: []
  +subClasses: []
  +embeddedClasses: []
  +namedQueries: []
  +namedNativeQueries: []
  +sqlResultSetMappings: []
  +identifier: array:1 [▶]
  +inheritanceType: 1
  +generatorType: 4
  +fieldMappings: array:9 [▼                   <-------
    "id" => array:9 [▶]
    "firstname" => array:8 [▶]
    "lastname" => array:8 [▶]
    "locale" => array:8 [▶]
    "timezone" => array:8 [▶]
    "phone" => array:8 [▶]
    "twoStepCode" => array:8 [▶]
    "created" => array:8 [▶]
    "updated" => array:8 [▶]
  ]
```

As you can see in the last one, only 9 mapped fields which are the ones declared in my User.php class. Seems the parent class  (FOS\UserBundle\Model\User) fields declared fields are not mapped for some reason.

I have dig into Doctrine source code and found this function [addInheritedFields](https://github.com/doctrine/orm/blob/2.7.x/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L410) responsible for adding inherited fields. This seems to be called and the parent fields are found and correct, but somewhere after this information gets lost.

Any ideas ?
Thanks in advance for the help.

**Comment by dcatz** [comment]
I have managed to fix it by manually setting FOSUserBundle mappings for my other connection (sa)

```
sa:
  connection: sa
  naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
  mappings:
      ...
      FOSUserBundle:
          type: xml
          dir: '%kernel.root_dir%/../vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping'
          prefix: FOS\UserBundle\Model
          is_bundle: false
      SonataMediaBundle: ~
      SonataUserBundle: ~
```
