### ISSUE TITLE
Add the ability to disable global_search 

### ISSUE THREAD

**Issue by BillyMorgan** [sonata-project/SonataUserBundle#1683]
I'm not entirely sure if this is a bug, or a feature, or me being a dolt but I wanted to exclude the user admin from the global search and the only way I could do it was to completely re-implement the service like this:
```
  sonata.user.admin.user:
    class: Sonata\UserBundle\Admin\Model\UserAdmin
    arguments:
      $userManager: '@sonata.user.manager.user'
    autowire: false
    autoconfigure: false
    tags:
      - name: sonata.admin
        model_class: Entity\User
        group: sonata_user
        manager_type: orm
        global_search: false
        label: users
        translation_domain: SonataUserBundle
        label_translator_strategy: sonata.admin.label.strategy.underscore
        icon: <i class='fa fa-users'></i>
```
All of this, just because I needed to add `global_search: false`. Is there already a better way to do this? If not, is the correct fix to extend the configuration to allow for the extra tag attribute? If so, I could give it a crack.
