### ISSUE TITLE
Any information about the "Impersonating" feature ?

### ISSUE THREAD

**Issue by jcrombez** [sonata-project/SonataUserBundle#174]
I have a working installation of SonataUserBundle but in the corresponding column of my users list, i see "-" instead of the link to switch to the wanted account.

The only thing i found in the documentation is this :

```yaml
    impersonating:
        route:                page_slug
        parameters:           { path: / }
```

But with no other information on what it is and how to get the feature working.

Anyone managed to do it ?
