### ISSUE TITLE
Documentation for extending the bundle is incorrect/incomplete

### ISSUE THREAD

**Issue by benglass** [sonata-project/SonataUserBundle#286]
The documentation on creating your own extended Application/Sonata/UserBundle so you can provide your User/Group entities does not seem to be in the right order as it instructs you to add configuration items for a bundle that doesn't exist yet before you are running the extends command.

For example it says to add this configuration

``` yml
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
```

Before it instructs you to run the extends command. The Application bundle doesnt exist yet so using these settings breaks your configuration and makes it so you cant run the command (you get an error about ApplicationSonataUserBundle not being a registered bundle and also that the user class/group class dont exist.

The solution I found was to set the user/group class to the ones from FOS user bundle (since they are required in the configuration) even though they are mapped superclasses and not entities (probably any class would work at this point with a valid namespace) and also commenting out the ApplicationSonataUserBundle from the mappings since it doesnt exist yet.

``` yml
fos_user:
    db_driver: orm
    user_class: FOS\UserBundle\Entity\User

sonata_user:
    class:
        user:        FOS\UserBundle\Entity\User
        group:      FOS\UserBundle\Entity\Group

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    # ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
```

Only then was I able to run the extends command and then go and fix the config.

Did I miss something or are the instructions just unclear in terms of the order you have to do things in

http://sonata-project.org/bundles/user/master/doc/reference/installation.html
