### ISSUE TITLE
Logic problem in the installation docs

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataUserBundle#405]
In the installation docs, you tell people to configure `fos_user` like this: 

``` yaml
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User


    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group        
        group_manager: sonata.user.orm.group_manager
```

Then, you tell them to extend the bundle, which will generate the aforementionened `User` and `Group` classes. Of course, this fails, as does any other symfony command (like `cache:clear`) with a message saying that `Application\Sonata\UserBundle\Entity\User` does not exist (they haven't be generated yet).

A workaround I found is to configure `fos_user` with classes that actually exist (like the `BaseUser` class of the SonataUserBundle), then generate the bundle, and then use the generated classes.
