### ISSUE TITLE
Wrong logout URL using url() instead of path()

### ISSUE THREAD

**Issue by samuel4x4** [sonata-project/SonataUserBundle#485]
https://github.com/sonata-project/SonataUserBundle/blob/master/Resources/views/Admin/Core/user_block.html.twig#L5

Why is there used url('...') instead of path('...')?

I noticed everywhere in SonataUserBundle the twig function path() is used, the url() one is present in just a few places. 

The url() generates a wrong absolute URL in my project, but path() works, I think the relative URL should be used.

Thank you.

**Comment by webdevilopers** [comment]
My routing file:
```yaml
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
```

The logout route is set in SonataUserBundle/Resources/config/routing/admin_security.xml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>

<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing http://symfony.com/schema/routing/routing-1.0.xsd">

    <route id="sonata_user_admin_security_login" pattern="/login">
        <default key="_controller">SonataUserBundle:AdminSecurity:login</default>
    </route>

    <route id="sonata_user_admin_security_check" pattern="/login_check">
        <default key="_controller">SonataUserBundle:AdminSecurity:check</default>
    </route>

    <route id="sonata_user_admin_security_logout" pattern="/logout">
        <default key="_controller">SonataUserBundle:AdminSecurity:logout</default>
    </route>
</routes>
```

But also in SonataUserBundle/Resources/config/routing/sonata_security_1.xml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>

<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing http://symfony.com/schema/routing/routing-1.0.xsd">

    <route id="fos_user_security_login" pattern="/login">
        <default key="_controller">SonataUserBundle:SecurityFOSUser1:login</default>
    </route>

    <route id="fos_user_security_check" pattern="/login_check">
        <default key="_controller">SonataUserBundle:SecurityFOSUser1:check</default>
        <requirement key="_method">POST</requirement>
    </route>

    <route id="fos_user_security_logout" pattern="/logout">
        <default key="_controller">SonataUserBundle:SecurityFOSUser1:logout</default>
    </route>

    <route id="sonata_user_security_login" pattern="/login">
        <default key="_controller">SonataUserBundle:SecurityFOSUser1:login</default>
    </route>

    <route id="sonata_user_security_check" pattern="/login_check">
        <default key="_controller">SonataUserBundle:SecurityFOSUser1:check</default>
        <requirement key="_method">POST</requirement>
    </route>

    <route id="sonata_user_security_logout" pattern="/logout">
        <default key="_controller">SonataUserBundle:SecurityFOSUser1:logout</default>
    </route>

</routes>
```

This should simply set routings for `logout` and `admin/logout`.
My firewalls look fine too:

```yaml
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:
                path:           /logout
            anonymous:          true
            
            # Session liftime
            remember_me:
                key: '%secret%'
                lifetime: 28800
            
            # Sonata User Impersonating
            switch_user: true

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /admin/login_check
            logout:
                path:           /admin/logout
            anonymous:          false
```

But still I get **You must activate the logout in your security firewall configuration.**

Still can't see what's wrong in config. Wrong order maybe, @stof ?
