### ISSUE TITLE
Symfony2 / User : Class does not exist

### ISSUE THREAD

**Issue by Philoow** [sonata-project/SonataUserBundle#505]
Hello ! 

Well, before starting to ask something i would like to say happy new year to everyone, yes i know it's tomorrow :) 

So :
I actually work on a custom bundle that user SonataUserBundle. Instead of creating a ApplicationSonataUserBundle i choosed to put all files in my custom bundle but it dosent work very well..I can list my users (that i've created with a command line) but i can"t add one. I've got this error when i click on "add" from the dashboard : 

Class does not exist
500 Internal Server Error - ReflectionException

The structure of my project looks like this : 

This is My kernel:

```
// Dependencies
new Sonata\CoreBundle\SonataCoreBundle(),
new Sonata\BlockBundle\SonataBlockBundle(),

// UserBundle
new FOS\UserBundle\FOSUserBundle(),
new Sonata\UserBundle\SonataUserBundle('FOSUserBundle'),
new Knp\Bundle\MenuBundle\KnpMenuBundle(),

// AdminBundle
new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
new Sonata\AdminBundle\SonataAdminBundle(),

//Custom
//new Application\Sonata\UserBundle\ApplicationSonataUserBundle(),
new Jcd\LiteyearBundle\JcdLiteyearBundle(),
```

my routing.yml

```
#UserBundle
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
```

my config.yml :

```
#UserBundle
sonata_user:
    security_acl: true
    manager_type: orm
    class:
        user: Jcd\LiteyearBundle\Entity\User
        group: Jcd\LiteyearBundle\Entity\Group
    admin:
        user:
            class: Jcd\LiteyearBundle\Admin\UserAdmin
            controller: SonataAdminBundle:CRUD
            translation: SonataUserBundle
        group:
            class: Jcd\LiteyearBundle\Admin\GroupAdmin
            controller: SonataAdminBundle:CRUD
            translation: SonataUserBundle

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Jcd\LiteyearBundle\Entity\User

    group:
        group_class:   Jcd\LiteyearBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

parameters:
     sonata.user.admin.user.entity: Jcd\LiteyearBundle\Entity\User
     sonata.user.admin.group.entity: Jcd\LiteyearBundle\Entity\Group
```

and this is my User Entity :

...
<?php

namespace Jcd\LiteyearBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Sonata\UserBundle\Model\UserInterface;

```
/**
 * @ORM\Entity
 * @ORM\Table(name="User")
 */
class User extends BaseUser implements UserInterface
{

/**
 * @ORM\Id
 * @ORM\Column(type="integer")
 * @ORM\GeneratedValue(strategy="AUTO")
 */
protected $id;

/**
 * @var \DateTime
 *
 * @ORM\Column(name="birthday", type="datetime", nullable=true)
 */
protected $birthday;

/**
 * @var string
 *
 * @ORM\Column(name="birthday_place", type="string", length=255, nullable=true)
 */
protected $birthday_place;

/**
 * @var string
 *
 * @ORM\Column(name="address1", type="string", length=255, nullable=true)
 */
protected $address1;

/**
 * @var string
 *
 * @ORM\Column(name="address2", type="string", length=255, nullable=true)
 */
protected $address2;

/**
 * @var string
 *
 * @ORM\Column(name="zipcode", type="string", length=5, nullable=true)
 */
protected $zipcode;

/**
 * @var string
 *
 * @ORM\Column(name="city", type="string", length=255, nullable=true)
 */
protected $city;


/**
 * @ORM\OneToOne(targetEntity="Jcd\LiteyearBundle\Entity\TeamUser", mappedBy="user")
 * @ORM\JoinColumn(nullable=true)
 */
protected $team_user;


/**
 * @ORM\OneToOne(targetEntity="Jcd\LiteyearBundle\Entity\TeamLeader", mappedBy="user")
 * @ORM\JoinColumn(nullable=true)
 */
protected $team_leader;


/**
 * Get id
 *
 * @return integer
 */
public function getId()
{
    return $this->id;
}

public function setTeamUser(TeamUser $tu)
{
    $this->team_user = $tu;
}

public function getTeamUser()
{
    return $this->team_user;
}

public function setTeamLeader(TeamLeader $tl)
{
    $this->team_leader = $tl;
}

public function getTeamLeader()
{
    return $this->team_leader;
}
}
```

I really don't understand what i missed. I've done other entity that use the user and groups and all works like a charm. But when i try to create an User it's broken ...

Does anybody have the same problem or know the solution ?
