### ISSUE TITLE
Nice to have: Make impersonating exit url configurable

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataUserBundle#528]
Currently the impersonating route can be configured:

``` yaml
sonata_user:
    impersonating:
        route:  sonata_admin_dashboard    
```

I would like the allowed to switch user to return to the user list when exiting. I cannot use the user list as impersonating route since the User I am switching to may not have the permission to view the user list.

A workaround is to override the existing template block:
https://github.com/sonata-project/SonataUserBundle/blob/master/Resources/views/Admin/Core/user_block.html.twig#L14
resp.
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Core/user_block.html.twig

It would be nice to have this route configurable too:

``` yaml
sonata_user:
    impersonating:
        route:  sonata_admin_dashboard    
        exit_route: sonata_admin_user_list
```

Opinions?
