### ISSUE TITLE
The service "sonata.user.serializer.handler.user" has a dependency on a non-existent service "sonata.user.manager.user".

### ISSUE THREAD

**Issue by houss2040** [sonata-project/SonataUserBundle#532]
Hello  , 
I want to install SonataUserBundle with MongoDb database , 
this is my configuration files :  

    fos_user:
         db_driver:      mongodb 
         firewall_name:  main
         user_class:     Sonata\UserBundle\Document\BaseUser

    group:
        group_class:   Sonata\UserBundle\Document\BaseGroup
        group_manager: sonata.user.mongodb.user_manager 

    service:
        user_manager: sonata.user.mongodb.group_manager

    sonata_user:
       security_acl: true
       manager_type: mongodb # can be orm or mongodb

      sonata_admin:
          title:      Admin
          #title_logo: bundles/acmedemo/img/fancy_acme_logo.png

My  AppKernel :  

           //knp
            new Knp\Bundle\MarkdownBundle\KnpMarkdownBundle(),
            new Knp\Bundle\MenuBundle\KnpMenuBundle(),
            
            //fos
            new FOS\ElasticaBundle\FOSElasticaBundle(),
            new FOS\UserBundle\FOSUserBundle(),
            
            //mongo
            new Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle(),
            
            //sonata
            new Sonata\FormatterBundle\SonataFormatterBundle(),
            new Sonata\DoctrineMongoDBAdminBundle\SonataDoctrineMongoDBAdminBundle(),
            new Sonata\AdminBundle\SonataAdminBundle(),
            new Sonata\CoreBundle\SonataCoreBundle(),
            new Sonata\BlockBundle\SonataBlockBundle(),
            new Sonata\UserBundle\SonataUserBundle(),
            new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),

My composer.json 

       "sonata-project/doctrine-mongodb-admin-bundle": "2.3.0",
        "doctrine/mongodb-odm-bundle": "3.0.*@dev",
        "doctrine/mongodb-odm": "1.0.*@dev",
        "doctrine/doctrine-fixtures-bundle": "~2.2.0@dev",
        "sonata-project/user-bundle": "2.3.*@dev",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
        "sonata-project/formatter-bundle": "~2.3",
        "friendsofsymfony/elastica-bundle": "~3.0",
        "sonata-project/doctrine-orm-admin-bundle": "2.4.*@dev"

I have always this exception 

The service "sonata.user.serializer.handler.user" has a dependency on a non-existent service "sonata.user.manager.user".

Help Please.

**Comment by OskarStark** [comment]
this is weird:

````
group:
    group_class:   Sonata\UserBundle\Document\BaseGroup
    group_manager: sonata.user.mongodb.user_manager 

service:
    user_manager: sonata.user.mongodb.group_manager
```

this seems to be correct:
````
group:
    group_class:   Sonata\UserBundle\Document\BaseGroup
    group_manager: sonata.user.mongodb.group_manager 

service:
    user_manager: sonata.user.mongodb.user_manager
```
