### ISSUE TITLE
override registration form in SonataUserBundle

### ISSUE THREAD

**Issue by KEFIR4UK** [sonata-project/SonataUserBundle#540]
Hi. I'm stuck on this problem few days. I tryed add fiield "age" in registration form,but i got this error:

Method "age" for object "Symfony\Component\Form\FormView" does not exist in FOSUserBundle:Registration:register_content.html.twig at line 104

I don't figure out what i do wrong.
```php
    //app/Application/Sonata/UserBundle/Entity/User.php

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank(message="Please enter your name.", groups={"Registration", "Profile"})
     */
     protected $age;


        public function getAge()
    {
        return $this->age;
    }

        public function setAge($age)
    {
         $this->a=$age;
    }
```
My formtype:

```php
//app/Application/Sonata/UserBundle/Form/Type/RegistrationFormType.php
namespace Application\Sonata\UserBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseType;

class RegistrationFormType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $builder->add('age');
    }

    public function getName()
    {
        return 'sonata_user_registration';
    }
        public function getParent()
    {
        return 'fos_user_registration';
    }

}
```
my config yml:
```yml
sonata_user:
    security_acl: false
    manager_type: orm
    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
    profile:
        register:
            # You may customize the registration forms over here
        form:
                type:                 sonata_user_registration
fos_user:
    db_driver:        orm # can be orm or mongodb (support is also available within FOSUser for couchdb, propel but none is given for SonataUserBundle)
    firewall_name:    main
    user_class:       Application\Sonata\UserBundle\Entity\User

    group:
        group_class:  Application\Sonata\UserBundle\Entity\Group

    profile:
        # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value
```

If i add in User.php proporties $age and ->add('age') in RegistrationFormType located in vendor/friendsosymfony/user-bundle/FOS/UserBundle/Entity/User,php and vendor/friendsosymfony/user-bundle/FOS/UserBundle/Form/Type/RegistrationFormType - it's work, but the proporties age didn't save in database. Also I tryed add variable in registration.html.twig:

```twig
//app/Application/Resources/ApplicationSonataUserBundle/views/Registrarion/register.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include ("FOSUserBundle:Registration:register_content.html.twig")with {'age':age} %}
{% endblock fos_user_content %}
```
But i got next error:
Variable "age" does not exist in FOSUserBundle:Registration:register.html.twig at line 4.
Has anyone idea how to solve this?

**Comment by KEFIR4UK** [comment]
I know why this error occure: RegistrationFormType from vendor/friemdsosymfony/userbundle/FOS/Form/Type/RegistrationFormType .php invoke instead from app/Application/Sonata/UserBundle/Form/Type/RegistrationFormType .php. But how do this vice versa?

**Comment by manuonet** [comment]
hi i try to do the same, but i got a different error... 

Unrecognized option "form" under "sonata_user.profile.register"

There seems to be a problem in my config.yml file, but i followed the instruction of SonataUserBundle.
````
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group
    
    profile:  # Profile Form (firstname, lastname, etc ...)
        
        register:
           form:
               type:           application_sonata_user_registration
               handler:        sonata.user.profile.form.handler
               name:           application_sonata_user_registration_form
               validation_groups: [Registration]
                                   
           # This allows you to specify where you want your user redirected once he activated his account
           confirm:
               redirect:
                   # Set it to false to disable redirection
                   route: 'sonata_user_profile_show'
                   route_parameters: ~
        
        form:
            type:               application_sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
        
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_change_password', label: 'link_change_password', domain: 'SonataUserBundle'}
#        - { route: 'sonata_customer_addresses', label: 'link_list_addresses', domain: 'SonataCustomerBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
#        - { route: 'sonata_order_index', label: 'order_list', domain: 'SonataOrderBundle'}
        
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.panelseniority, settings: { paneltype: "primary", title: "Ancienneté", fa: "clock-o", link: "#" }}
                
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Bienvenue !</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
                                
                - { position: center, type: sonata.block.service.panel, settings: { paneltype: "green", title: "Offre", fa: "database", number: "9", link: "#" }}
                - { position: center, type: sonata.block.service.rss, settings: { title: Offre d'emploi Onet, url: http://fr.groupeonet.com/rss/feed/offre_emploi }}
                
                #- { position: left, type: sonata.order.block.recent_orders, settings: { title: Recent Orders, number: 5, mode: public }}
                #- { position: right, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
                #- { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
                #- { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}
                
                - { position: right, type: sonata.block.service.panel, settings: { paneltype: "yellow", title: "Actu", fa: "newspaper-o", number: "15", link: "#" }}
                - { position: right, type: sonata.block.service.rss, settings: { title: Actualités Onet, url: http://fr.groupeonet.com/rss/feed/actualites }}
                
        
````

**Comment by OskarStark** [comment]
wrong indention:

```yaml
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group

    profile:  # Profile Form (firstname, lastname, etc ...)

        register:
           form:
               type:           application_sonata_user_registration
               handler:        sonata.user.profile.form.handler
               name:           application_sonata_user_registration_form
               validation_groups: [Registration]

           # This allows you to specify where you want your user redirected once he activated his account
           confirm:
               redirect:
                   # Set it to false to disable redirection
                   route: 'sonata_user_profile_show'
                   route_parameters: ~

            form:
                type:               application_sonata_user_profile
                handler:            sonata.user.profile.form.handler.default
                name:               sonata_user_profile_form
                validation_groups:  [Profile]

        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_change_password', label: 'link_change_password', domain: 'SonataUserBundle'}
#        - { route: 'sonata_customer_addresses', label: 'link_list_addresses', domain: 'SonataCustomerBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
#        - { route: 'sonata_order_index', label: 'order_list', domain: 'SonataOrderBundle'}

        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.panelseniority, settings: { paneltype: "primary", title: "Ancienneté", fa: "clock-o", link: "#" }}

                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Bienvenue !</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }

                - { position: center, type: sonata.block.service.panel, settings: { paneltype: "green", title: "Offre", fa: "database", number: "9", link: "#" }}
                - { position: center, type: sonata.block.service.rss, settings: { title: Offre d'emploi Onet, url: http://fr.groupeonet.com/rss/feed/offre_emploi }}

                #- { position: left, type: sonata.order.block.recent_orders, settings: { title: Recent Orders, number: 5, mode: public }}
                #- { position: right, type: sonata.timeline.block.timeline, settings: { max_per_page: 15 }}
                #- { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
                #- { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}

                - { position: right, type: sonata.block.service.panel, settings: { paneltype: "yellow", title: "Actu", fa: "newspaper-o", number: "15", link: "#" }}
                - { position: right, type: sonata.block.service.rss, settings: { title: Actualités Onet, url: http://fr.groupeonet.com/rss/feed/actualites }}
```

**Comment by manuonet** [comment]
Hi thanks a lot for your quick answer, but could you soecify where did you find a wrong indentation.
i checked all the lines with 4 spaces before strings.

**Comment by manuonet** [comment]
just for info, i am on Symfony 2.7 and sonata 2.2.4 and FOS User Bundle 1.3.6

**Comment by manuonet** [comment]
HI i tested on Symfony 2.3 and with the same config.yml, i did not have this error.
Is it a bug of Sonata User Bundle with Symfony 2.7?

**Comment by manuonet** [comment]
YEHHH i found the problem in the new configuration of SonataUserBundle.
In the previous configuration file 
vendor/sonata-project/user-bundle/DependencyInjection/Configuration.php
````
->arrayNode('register')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('type')->defaultValue('sonata_user_registration')->end()
                                        ->scalarNode('handler')->defaultValue('sonata.user.registration.form.handler.default')->end()
                                        ->scalarNode('name')->defaultValue('sonata_user_registration_form')->cannotBeEmpty()->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(array('Registration', 'Default'))
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('confirm')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('redirect')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->scalarNode('route')->defaultValue('sonata_user_profile_show')->end()
                                                ->arrayNode('route_parameters')
                                                    ->defaultValue(array())
                                                    ->prototype('array')->end()
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
````
And in the actual configuration file
vendor/sonata-project/user-bundle/DependencyInjection/Configuration.php
````
->arrayNode('register')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('confirm')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('redirect')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->scalarNode('route')->defaultValue('sonata_user_profile_show')->end()
                                                ->arrayNode('route_parameters')
                                                    ->defaultValue(array())
                                                    ->prototype('array')->end()
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
````
All the node about "register/form" is not present!
it's a bug...

**Comment by manuonet** [comment]
for information, i had the content above in the new vendor configuration file, and no error now....
not safe, but i hope that Sonata will correct and PR

**Comment by Invis1ble** [comment]
I have the same error (`Unrecognized option "form" under "sonata_user.profile.register"`), in my config.yml:
```yml
sonata_user:
    profile:
        register:
            form:
                type: user_registration
```
In my composer.json
```json
        "sonata-project/user-bundle": "~2.2",
```
which is resolved to
```json
            "name": "sonata-project/user-bundle",
            "version": "2.2.4",
```
