### ISSUE TITLE
How to set association between an existing entity and Sonata User entity?

### ISSUE THREAD

**Issue by cithukyaw** [sonata-project/SonataUserBundle#582]
I have [Sonata User Bundle installed](https://sonata-project.org/bundles/user/master/doc/reference/installation.html) and I got the generated `src/Application/Sonata/UserBundle`. I want to set `oneToMany` relationship between my existing entity "Property" and Sonata "User" entity.

So I added `manyToOne` in `MyBundle\Resources\config\doctrine\Property.orm.yml`:

```
MyBundle\Entity\Property:
    type: entity
    repositoryClass: MyBundle\Repository\PropertyRepository
    table: property

    // ...

    manyToOne:
        user:
            targetEntity: User
            inversedBy: users
            joinColumn:
                name: user_id
                referencedColumnName: id # fos_user_user.id
```

I copied 
- `src\Application\Sonata\UserBundle\Entity\User.php` to `src\MyBundle\Entity\User.php`
- `src\Application\Sonata\UserBundle\Entity\Group.php` to `src\MyBundle\Entity\Group.php` 

I updated `app\config\config.yml` with those entity information:

```
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     MyBundle\Entity\User

    group:
        group_class:   MyBundle\Entity\Group
```

Then, I added `src\EstateBundle\Resources\config\doctrine\User.orm.yml` with `oneToMay` relationship to "Property":

```
MyBundle\Entity\User:
    type: entity
    repositoryClass: MyBundle\Repository\UserRepository
    table: fos_user_user
    options:
        collate: utf8_general_ci
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            options:
                unsigned: true
    oneToMany:
        properties:
            targetEntity: Property
            mappedBy: property
```

The below is my updated "User" entity after running `doctrine:generate:entities`. That seems correct. It has `$properties` and its getter/setter.

```
namespace MyBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $properties;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
        $this->properties = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add properties
     *
     * @param \EstateBundle\Entity\Property $properties
     * @return User
     */
    public function addProperty(\EstateBundle\Entity\Property $properties)
    {
        $this->properties[] = $properties;

        return $this;
    }

    /**
     * Remove properties
     *
     * @param \EstateBundle\Entity\Property $properties
     */
    public function removeProperty(\EstateBundle\Entity\Property $properties)
    {
        $this->properties->removeElement($properties);
    }

    /**
     * Get properties
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getProperties()
    {
        return $this->properties;
    }
}
```

After running `doctrine:schema:update --force`, I got the error:

> [Doctrine\DBAL\Schema\SchemaException]  
> The table with name 'mydb_name.fos_user_user' already exists. 

What I'm doing is correct? Any help will be greatly appreciated.

**Comment by vincenttouzet** [comment]
You also have to change the  files 
* Application\Sonata\UserBundle\Resources\config\doctrine\User.orm.xml
* Application\Sonata\UserBundle\Resources\config\doctrine\Group.orm.xml

and change entity to mapped-superclass

```xml
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                  http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <mapped-superclass name="Application\Sonata\UserBundle\Entity\User">

        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>

    </mapped-superclass>

</doctrine-mapping>
```

I also updated the config of sonata_user : 

```yml
# app/config/config.yml
sonata_user:
    class:                  # Entity Classes
        user:               MyBundle\Entity\User
        group:              MyBundle\Entity\Group
```
