### ISSUE TITLE
Custom Validation YML for Registration Form getting ignored

### ISSUE THREAD

**Issue by sujayjaju** [sonata-project/SonataUserBundle#611]
I wanted to add custom validation on my registration form. So I created a validation.yml for a new validation group:

``` yaml
#src/Application/Sonata/UserBundle/Resources/config/validation.yml
Application\Sonata\UserBundle\Entity\User:
    properties:
        username:
            - Length:
                min: 10
                minMessage: Not long enough
                max: 31
                maxMessage: Too long
                groups: [CustomRegistraion]
```

I then updated the config.yml to use the CustomRegistraion group

``` yaml
sonata_user:
# ... other config ...

    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    profile:
        register:
            form:
                type:                 custom_user_registration
                handler:              sonata.user.registration.form.handler.default
                name:                 custom_user_registration
                validation_groups:    [CustomRegistration]
```

But the validation yml never comes into play during registration. If I have a syntax error in the file, it breaks the app, so it is getting loaded - but gets ignored when a user registers. What am I missing?
