### ISSUE TITLE
Unable to use steps in documentation to run  sonata:easy-extends:generate

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataUserBundle#643]
I am told to add these lines to config.yml

```
user_class:     Application\Sonata\UserBundle\Entity\User


group:
    group_class:   Application\Sonata\UserBundle\Entity\Group
```

Later on I am told to run this command:

php app/console sonata:easy-extends:generate SonataUserBundle -d src

I then get this error: 

  [Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'Application\Sonata\UserBundle\Entity\User' does not exist

Which seems logical since I am putting things in the documentation that don't exist.

**Comment by Neodork** [comment]
If you're experiencing this following this tutorial:
https://sonata-project.org/bundles/user/2-2/doc/reference/installation.html

You should make sure you comment ApplicationSonataUserBundle in the config before running the command.

```yaml
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    #ApplicationSonataUserBundle: ~ <--- Note how I commented this line compared to the 
                    SonataUserBundle: ~
```

Uncomment when the command has finished running.
