### ISSUE TITLE
Configure check_path in firewall exception

### ISSUE THREAD

**Issue by DevMaster112** [sonata-project/SonataUserBundle#665]
Hay guys. 

My provider does an update of the managed root server and now i got this exception:

```
Uncaught PHP Exception RuntimeException: "You must configure the check path to be handled by the firewall using form_login in your security firewall configuration." at /usr/local/www/apache24/noexec/plusquam/shared/vendor/sonata-project/user-bundle/Controller/AdminSecurityController.php line 110 {"exception":"[object] (RuntimeException(code: 0): You must configure the check path to be handled by the firewall using form_login in your security firewall configuration. at /usr/local/www/apache24/noexec/plusquam/shared/vendor/sonata-project/user-bundle/Controller/AdminSecurityController.php:110)"}
```

I can't figure out where the problem is. I didn't changed anything to my symfony2 project and i didn't changed the security.yml in my app/config folder. 

this is my firewall in security.yml:

``` yaml
firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        qis:
            pattern:            /qis(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    true
                check_path:     sonata_user_admin_security_check

            logout:
                path:           sonata_user_admin_security_logout
            anonymous:          true

            # Session liftime
            remember_me:
                key: '%secret%'
                lifetime: 28800

            # Sonata User Impersonating
            switch_user: true

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    true
                default_target_path: /qis/contract/list
                check_path:     sonata_user_admin_security_check
                failure_path:   null
            logout:
                path:           sonata_user_admin_security_logout
            anonymous:          true

            # Session liftime
            remember_me:
                key: '%secret%'
                lifetime: 28800

            # Sonata User Impersonating
            switch_user: true

```

Any ideas? 
I have no idea how to solve this issue.
