### ISSUE TITLE
Model class "Application\Sonata\UserBundle\Admin\UserAdmin" does not correspond to manager type "orm".

### ISSUE THREAD

**Issue by maavia10** [sonata-project/SonataUserBundle#944]
```yaml
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Application\Sonata\UserBundle\Admin\UserAdmin # there define your extended admin class
            controller:     SonataUserBundle:UserCURD
            translation:    SonataUserBundle
```
get this above error while extending user Admin class to change in user form
